/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo.telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc27sala06
 */
public class Cadastros extends javax.swing.JFrame {

    /**
     * Creates new form Cadastros
     */
    public Cadastros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CadUsua = new javax.swing.JButton();
        CadADMZoo = new javax.swing.JButton();
        CadZoo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Agendamento de tour", jPanel5);

        CadUsua.setText("Cadastrar Usuario");
        CadUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadUsuaActionPerformed(evt);
            }
        });

        CadADMZoo.setText("Cadastrar Adm de Zoologico");
        CadADMZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadADMZooActionPerformed(evt);
            }
        });

        CadZoo.setText("Cadastrar Zoologico");
        CadZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadZooActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadZoo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(CadADMZoo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(CadUsua, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CadUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CadADMZoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CadZoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastros", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    CadUsuarios usuario, adm;
    
    private void CadUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadUsuaActionPerformed
        usuario = new CadUsuarios();
        usuario.setVisible(true);
        usuario.setResizable(false);
        usuario.setLocationRelativeTo(null);
        usuario.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_CadUsuaActionPerformed

    private void CadADMZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadADMZooActionPerformed
        String senha = "123", test;
        try{
            test = JOptionPane.showInputDialog("Necessario Permissão de Administrador\nDigite a senha de ADM:");
            if(test.equals(senha)){
                adm = new CadUsuarios();
                adm.setVisible(true);
                adm.setResizable(false);
                adm.setLocationRelativeTo(null);
                adm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            }else{
                JOptionPane.showMessageDialog(null, "Senha incorreta!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Senha incorreta!");
        }
    }//GEN-LAST:event_CadADMZooActionPerformed
    CadZoo zoologico;
    private void CadZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadZooActionPerformed
        String senha = "123", test;
        try{
            test = JOptionPane.showInputDialog("Necessario Permissão de Administrador\nDigite a senha de ADM:");
            if(test.equals(senha)){
                zoologico = new CadZoo();
                zoologico.setVisible(true);
                zoologico.setResizable(false);
                zoologico.setLocationRelativeTo(null);
                zoologico.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            }else{
                JOptionPane.showMessageDialog(null, "Senha incorreta!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Senha incorreta!");
        }
    }//GEN-LAST:event_CadZooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadADMZoo;
    private javax.swing.JButton CadUsua;
    private javax.swing.JButton CadZoo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
