/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo.telas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.border.*;

/**
 *
 * @author Bruno
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        //Borda default Pesquisa de Zoo
        CompoundBorder innerCompound = null;
        CompoundBorder outerCompound = null;

        innerCompound = new CompoundBorder(new EmptyBorder(0, 8, 0, 8), new EmptyBorder(0, 0, 0, 0));
        outerCompound = new CompoundBorder(new LineBorder(new Color(211, 211, 211), 1), innerCompound);

        initComponents();

        //Aplicação das bordas default
        zoo_LocateByUfTbx.setBorder(outerCompound);
        zoo_locateByCityTbx.setBorder(outerCompound);
        zoo_locateByZooTbx.setBorder(outerCompound);
        perfil_CpfTbx.setBorder(outerCompound);
        perfil_NomeTbx.setBorder(outerCompound);
        perfil_EmailTbx.setBorder(outerCompound);
        principal_locateByZooTbx.setBorder(outerCompound);

        //Configuração do Icone
        this.setIconImage(new ImageIcon(getClass().getResource("/zoo/Imagens/iCON.png")).getImage());

        //Background botões
        btnPrincipal.setBackground(new Color(0, 0, 0, 0));
        btnPerfil.setBackground(new Color(0, 0, 0, 0));
        btnSupp.setBackground(new Color(0, 0, 0, 0));
        btnZoo.setBackground(new Color(0, 0, 0, 0));
        Sair.setBackground(new Color(0, 0, 0, 0));
        Sair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        botaoBug.setBackground(new Color(0, 0, 0, 0));
        botaoDenuncia.setBackground(new Color(0, 0, 0, 0));
        botaoDuvida.setBackground(new Color(0, 0, 0, 0));
        zoo_locateByZoo.setBackground(new Color(0, 0, 0, 0));
        zoo_locateByUfCity.setBackground(new Color(0, 0, 0, 0));

        //Configuração inicial do MENU
        selectImg_Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Suport.setIcon(null);
        selectImg_Zoo.setIcon(null);
        selectImg_Perfil.setIcon(null);

        //Configuração inicial do SUPORTE
        jTextFieldSuporte.setVisible(false);
        jLabelEnviar.setVisible(false);

        // configuração inicia de perfil
        perfil_CpfBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelAlterarSenha.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelAlterarImagem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        perfil_EmailBtn.setBackground(new Color(0, 0, 0, 0));
        perfil_NomeBtn.setBackground(new Color(0, 0, 0, 0));
        perfil_CpfBtn.setBackground(new Color(0, 0, 0, 0));

        //PlaceHolder
    }

    /**
     *
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnPrincipal = new javax.swing.JButton();
        btnZoo = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        selectImg_Principal = new javax.swing.JLabel();
        selectImg_Zoo = new javax.swing.JLabel();
        selectImg_Perfil = new javax.swing.JLabel();
        selectImg_Suport = new javax.swing.JLabel();
        jfPainel = new javax.swing.JTabbedPane();
        jPanelZoo2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        principal_locateByZooTbx = new javax.swing.JTextField();
        principal_PesquisaBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanelZoo1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        zoo_locateByZooTbx = new javax.swing.JTextField();
        zoo_locateByZoo = new javax.swing.JButton();
        zoo_LocateByUfTbx = new javax.swing.JTextField();
        zoo_locateByCityTbx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        zoo_locateByUfCity = new javax.swing.JButton();
        jPanelZoo = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelAlterarImagem = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelAlterarSenha = new javax.swing.JLabel();
        perfil_CpfTbx = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        perfil_EmailTbx = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        perfil_NomeTbx = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        perfil_NomeBtn = new javax.swing.JButton();
        perfil_EmailBtn = new javax.swing.JButton();
        perfil_CpfBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanelP = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabelEnviar = new javax.swing.JLabel();
        jTextFieldSuporte = new javax.swing.JTextField();
        botaoDenuncia = new javax.swing.JButton();
        botaoBug = new javax.swing.JButton();
        botaoDuvida = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel12.setText("jLabel12");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        btnPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setText("Principal");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 30));

        btnZoo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZoo.setForeground(new java.awt.Color(255, 255, 255));
        btnZoo.setText("Pesquisar");
        btnZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZooActionPerformed(evt);
            }
        });
        getContentPane().add(btnZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 30));

        btnPerfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 30));

        btnSupp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSupp.setForeground(new java.awt.Color(255, 255, 255));
        btnSupp.setText("Suporte");
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 30));

        jPanel1.setBackground(new Color(0,0,0,0) );

        jLabel7.setBackground(new Color(0,0,0,0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/PessoaIcon.png"))); // NOI18N
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 90));

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/bota_sair.png"))); // NOI18N
        Sair.setMaximumSize(new java.awt.Dimension(120, 83));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 50, 60));

        jLabel3.setBackground(new Color(0,0,0,0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SAIR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        selectImg_Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png"))); // NOI18N
        getContentPane().add(selectImg_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 270, 50));

        selectImg_Zoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png"))); // NOI18N
        getContentPane().add(selectImg_Zoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 210, 270, 50));

        selectImg_Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png"))); // NOI18N
        getContentPane().add(selectImg_Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 270, 50));

        selectImg_Suport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png"))); // NOI18N
        getContentPane().add(selectImg_Suport, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, 270, 50));

        jfPainel.setBackground(new Color (0,0,0,0));
        jfPainel.setEnabled(false);

        jPanelZoo2.setBackground(new Color(0,0,0,0));
        jPanelZoo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/iCON50-50.png"))); // NOI18N

        principal_locateByZooTbx.setText("Digite sua pesquisa!");
        principal_locateByZooTbx.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        principal_locateByZooTbx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                principal_locateByZooTbxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                principal_locateByZooTbxFocusLost(evt);
            }
        });
        principal_locateByZooTbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principal_locateByZooTbxActionPerformed(evt);
            }
        });

        principal_PesquisaBtn.setBackground(new java.awt.Color(255, 255, 255));
        principal_PesquisaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_lupa.png"))); // NOI18N
        principal_PesquisaBtn.setOpaque(false);
        principal_PesquisaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principal_PesquisaBtnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 102, 0));
        jLabel21.setText("Destaques");

        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new Color(0,0,0,70));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Zoo01");
        jPanel18.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel11.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new Color(0,0,0,70));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Zoo01");
        jPanel24.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel12.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new Color(0,0,0,70));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Zoo01");
        jPanel25.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel13.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel14.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel14MouseWheelMoved(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel14MouseReleased(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new Color(0,0,0,70));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Zoo01");
        jPanel26.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel14.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel15MouseExited(evt);
            }
        });
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new Color(0,0,0,70));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Zoo01");
        jPanel27.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel15.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel16MouseExited(evt);
            }
        });
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel28.setBackground(new Color(0,0,0,70));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Zoo01");
        jPanel28.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel16.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel17MouseExited(evt);
            }
        });
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBackground(new Color(0,0,0,70));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Zoo01");
        jPanel29.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel17.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel32MouseExited(evt);
            }
        });
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new Color(0,0,0,70));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Zoo01");
        jPanel33.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 27));

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(principal_locateByZooTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(principal_PesquisaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(principal_PesquisaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principal_locateByZooTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15))
        );

        jPanelZoo2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        jfPainel.addTab("", jPanelZoo2);

        jPanelZoo1.setBackground(new Color(0,0,0,0));
        jPanelZoo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        zoo_locateByZooTbx.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        zoo_locateByZoo.setBackground(new java.awt.Color(255, 255, 255));
        zoo_locateByZoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_lupa.png"))); // NOI18N
        zoo_locateByZoo.setOpaque(false);
        zoo_locateByZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoo_locateByZooActionPerformed(evt);
            }
        });

        zoo_LocateByUfTbx.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(211,211,211, 60)));
        zoo_LocateByUfTbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zoo_LocateByUfTbxKeyTyped(evt);
            }
        });

        zoo_locateByCityTbx.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(211,211,211, 60)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("UF");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Localizar Zoológico");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 0));
        jLabel11.setText("Ou escolha");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/iCON50-50.png"))); // NOI18N

        zoo_locateByUfCity.setBackground(new java.awt.Color(255, 255, 255));
        zoo_locateByUfCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_lupa.png"))); // NOI18N
        zoo_locateByUfCity.setOpaque(false);
        zoo_locateByUfCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoo_locateByUfCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(zoo_locateByZooTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zoo_locateByZoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zoo_LocateByUfTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zoo_locateByCityTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zoo_locateByUfCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 275, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 275, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zoo_locateByZooTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(zoo_locateByZoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(zoo_LocateByUfTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zoo_locateByCityTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(zoo_locateByUfCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jLabel14))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 205, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 205, Short.MAX_VALUE)))
        );

        jPanelZoo1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        jfPainel.addTab("", jPanelZoo1);

        jPanelZoo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelZoo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAlterarImagem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelAlterarImagem.setForeground(new java.awt.Color(0, 102, 0));
        jLabelAlterarImagem.setText("Alterar Imagem do Perfil");
        jPanel7.add(jLabelAlterarImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/iCON50-50.png"))); // NOI18N
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jLabelAlterarSenha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelAlterarSenha.setForeground(new java.awt.Color(0, 102, 0));
        jLabelAlterarSenha.setText("Alterar Senha");
        jPanel7.add(jLabelAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel7.add(perfil_CpfTbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 0));
        jLabel18.setText("CPF");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        perfil_EmailTbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil_EmailTbxActionPerformed(evt);
            }
        });
        jPanel7.add(perfil_EmailTbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 308, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 0));
        jLabel17.setText("Email");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel7.add(perfil_NomeTbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 229, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 0));
        jLabel16.setText("Nome");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        perfil_NomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/IconeEdit.png"))); // NOI18N
        jPanel7.add(perfil_NomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 30, 30));

        perfil_EmailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/IconeEdit.png"))); // NOI18N
        perfil_EmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil_EmailBtnActionPerformed(evt);
            }
        });
        jPanel7.add(perfil_EmailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 30, 30));

        perfil_CpfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/IconeEdit.png"))); // NOI18N
        perfil_CpfBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        perfil_CpfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil_CpfBtnActionPerformed(evt);
            }
        });
        jPanel7.add(perfil_CpfBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 30, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 102, 0));
        jLabel19.setText("Perfil");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanelZoo.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        jfPainel.addTab("", jPanelZoo);

        jPanelP.setBackground(new Color(0,0,0,0));
        jPanelP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 144, -1, -1));

        jLabelEnviar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEnviar.setForeground(new java.awt.Color(0, 102, 0));
        jLabelEnviar.setText("Enviar");
        jPanel9.add(jLabelEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 332, -1, -1));
        jPanel9.add(jTextFieldSuporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 187, 489, 127));

        botaoDenuncia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_denuncia.png"))); // NOI18N
        botaoDenuncia.setBorder(null);
        botaoDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDenunciaActionPerformed(evt);
            }
        });
        jPanel9.add(botaoDenuncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        botaoBug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_bugs.png"))); // NOI18N
        botaoBug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBugActionPerformed(evt);
            }
        });
        jPanel9.add(botaoBug, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 102, 105));

        botaoDuvida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_duvidas.png"))); // NOI18N
        botaoDuvida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDuvidaActionPerformed(evt);
            }
        });
        jPanel9.add(botaoDuvida, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 37, 95, 107));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/iCON50-50.png"))); // NOI18N
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 479, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 0));
        jLabel20.setText("Denuncia");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 0));
        jLabel22.setText("Bugs");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 0));
        jLabel24.setText("Duvidas");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jPanelP.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 410));

        jfPainel.addTab("", jPanelP);

        getContentPane().add(jfPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 560, 440));

        jLabel1.setBackground(new Color(0,0,0,0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/tela_principal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        //Definindo a Aba do Painel com guias a ser aberta
        jfPainel.setSelectedIndex(0);

        //Configurações de estetica
        selectImg_Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Zoo.setIcon(null);
        selectImg_Perfil.setIcon(null);
        selectImg_Suport.setIcon(null);
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZooActionPerformed
        //Definindo a Aba do Painel com guias a ser aberta
        jfPainel.setSelectedIndex(1);

        //Configurações de estetica
        selectImg_Principal.setIcon(null);
        selectImg_Zoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Perfil.setIcon(null);
        selectImg_Suport.setIcon(null);
    }//GEN-LAST:event_btnZooActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        //Definindo a Aba do Painel com guias a ser aberta
        jfPainel.setSelectedIndex(2);

        //Configurações de estetica
        selectImg_Principal.setIcon(null);
        selectImg_Zoo.setIcon(null);
        selectImg_Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Suport.setIcon(null);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        //Definindo a Aba do Painel com guias a ser aberta
        jfPainel.setSelectedIndex(3);

        //Configurações de estetica
        selectImg_Principal.setIcon(null);
        selectImg_Zoo.setIcon(null);
        selectImg_Perfil.setIcon(null);
        selectImg_Suport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
    }//GEN-LAST:event_btnSuppActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        //Variavel que recebe a confirmação do usuario (0 - Sim; 1 - Não);
        int escolha;

        //Apresentação do PopUp de saída
        escolha = JOptionPane.showConfirmDialog(rootPane, "Você deseja sair?", "Sair", JOptionPane.YES_NO_OPTION, 1, new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/iCON50-50.png")));

        if (escolha == 0) {
            //  System.exit(0);

            principal princ = new principal();
            Login login = new Login();

            princ.setVisible(false);
            login.setVisible(true);

            dispose();
        }
    }//GEN-LAST:event_SairActionPerformed

    private void zoo_LocateByUfTbxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zoo_LocateByUfTbxKeyTyped
        if (zoo_LocateByUfTbx.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_zoo_LocateByUfTbxKeyTyped

    private void zoo_locateByZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoo_locateByZooActionPerformed
        jTextFieldSuporte.setVisible(true);
        jLabelEnviar.setVisible(true);
    }//GEN-LAST:event_zoo_locateByZooActionPerformed

    private void botaoDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDenunciaActionPerformed
        jTextFieldSuporte.setVisible(true);
        jLabelEnviar.setVisible(true);
        botaoDenuncia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        botaoBug.setBorder(null);
        botaoDuvida.setBorder(null);
    }//GEN-LAST:event_botaoDenunciaActionPerformed

    private void botaoBugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBugActionPerformed
        jTextFieldSuporte.setVisible(true);
        jLabelEnviar.setVisible(true);
        botaoDenuncia.setBorder(null);
        botaoBug.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        botaoDuvida.setBorder(null);
    }//GEN-LAST:event_botaoBugActionPerformed

    private void botaoDuvidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDuvidaActionPerformed
        jTextFieldSuporte.setVisible(true);
        jLabelEnviar.setVisible(true);
        botaoDenuncia.setBorder(null);
        botaoBug.setBorder(null);
        botaoDuvida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_botaoDuvidaActionPerformed

    private void perfil_CpfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil_CpfBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfil_CpfBtnActionPerformed

    private void perfil_EmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil_EmailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfil_EmailBtnActionPerformed

    private void perfil_EmailTbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil_EmailTbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfil_EmailTbxActionPerformed

    private void zoo_locateByUfCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoo_locateByUfCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoo_locateByUfCityActionPerformed

    private void principal_PesquisaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principal_PesquisaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principal_PesquisaBtnActionPerformed

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        jPanel11.setBorder(null);
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        jPanel12.setBorder(null);
    }//GEN-LAST:event_jPanel12MouseExited

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        jPanel13.setBorder(null);
    }//GEN-LAST:event_jPanel13MouseExited

    private void jPanel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseReleased

    private void jPanel14MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel14MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseWheelMoved

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        jPanel14.setBorder(null);
    }//GEN-LAST:event_jPanel14MouseExited

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jPanel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseEntered
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel15MouseEntered

    private void jPanel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseExited
        jPanel15.setBorder(null);
    }//GEN-LAST:event_jPanel15MouseExited

    private void jPanel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseEntered
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel16MouseEntered

    private void jPanel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseExited
        jPanel16.setBorder(null);
    }//GEN-LAST:event_jPanel16MouseExited

    private void jPanel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseExited
        jPanel17.setBorder(null);
    }//GEN-LAST:event_jPanel17MouseExited

    private void jPanel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseEntered
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel17MouseEntered

    private void jPanel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel32MouseEntered
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
    }//GEN-LAST:event_jPanel32MouseEntered

    private void jPanel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel32MouseExited
        jPanel32.setBorder(null);
    }//GEN-LAST:event_jPanel32MouseExited

    private void principal_locateByZooTbxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_principal_locateByZooTbxFocusGained
        if (principal_locateByZooTbx.getText().equals("Digite sua pesquisa!")) {
            principal_locateByZooTbx.setText("");
            principal_locateByZooTbx.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_principal_locateByZooTbxFocusGained

    private void principal_locateByZooTbxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_principal_locateByZooTbxFocusLost
        if (principal_locateByZooTbx.getText().isEmpty()) {
            principal_locateByZooTbx.setForeground(Color.GRAY);
            principal_locateByZooTbx.setText("Digite sua pesquisa!");
        }
    }//GEN-LAST:event_principal_locateByZooTbxFocusLost

    private void principal_locateByZooTbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principal_locateByZooTbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principal_locateByZooTbxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton botaoBug;
    private javax.swing.JButton botaoDenuncia;
    private javax.swing.JButton botaoDuvida;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnSupp;
    private javax.swing.JButton btnZoo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlterarImagem;
    private javax.swing.JLabel jLabelAlterarSenha;
    private javax.swing.JLabel jLabelEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelP;
    private javax.swing.JPanel jPanelZoo;
    private javax.swing.JPanel jPanelZoo1;
    private javax.swing.JPanel jPanelZoo2;
    private javax.swing.JTextField jTextFieldSuporte;
    private javax.swing.JTabbedPane jfPainel;
    private javax.swing.JButton perfil_CpfBtn;
    private javax.swing.JTextField perfil_CpfTbx;
    private javax.swing.JButton perfil_EmailBtn;
    private javax.swing.JTextField perfil_EmailTbx;
    private javax.swing.JButton perfil_NomeBtn;
    private javax.swing.JTextField perfil_NomeTbx;
    private javax.swing.JButton principal_PesquisaBtn;
    private javax.swing.JTextField principal_locateByZooTbx;
    private javax.swing.JLabel selectImg_Perfil;
    private javax.swing.JLabel selectImg_Principal;
    private javax.swing.JLabel selectImg_Suport;
    private javax.swing.JLabel selectImg_Zoo;
    private javax.swing.JTextField zoo_LocateByUfTbx;
    private javax.swing.JTextField zoo_locateByCityTbx;
    private javax.swing.JButton zoo_locateByUfCity;
    private javax.swing.JButton zoo_locateByZoo;
    private javax.swing.JTextField zoo_locateByZooTbx;
    // End of variables declaration//GEN-END:variables

}
