/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo.telas;

import zoo.zoologicos.Zoologicos;
import java.awt.Color;
import java.awt.Cursor;
import static java.lang.Integer.parseInt;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import zoo.Adm.*;
import zoo.main.InicioProg;

/**
 *
 * @author Bruno
 */
public class TelaAdmSistema extends javax.swing.JFrame {

    /**
     * Creates new form CadZoologicos
     */
    //ZooIndex
    int lastSelectedIndex = -1;

    public TelaAdmSistema() {
        initComponents();

        jTabbedPane1.setBackground(new Color(0, 0, 0, 0));
        jTabbedPane2.setBackground(new Color(0, 0, 0, 0));
        jTabbedPane3.setBackground(new Color(0, 0, 0, 0));
        jButtonCadAdmSistema.setBackground(new Color(0, 0, 0, 0));
        jButtonCadZoo.setBackground(new Color(0, 0, 0, 0));
        jButtonExcluirZoo.setBackground(new Color(0, 0, 0, 0));
        jButtonCadAdmZoo.setBackground(new Color(0, 0, 0, 0));
        jButtonZoo.setBackground(new Color(0, 0, 0, 0));
        jButtonAdm.setBackground(new Color(0, 0, 0, 0));
        jButtonUsu.setBackground(new Color(0, 0, 0, 0));
        jButton17.setBackground(new Color(0, 0, 0, 0));
        jButton1.setBackground(new Color(0, 0, 0, 0));
        jButton14.setBackground(new Color(0, 0, 0, 0));
        jButton3.setBackground(new Color(0, 0, 0, 0));
        jButton16.setBackground(new Color(0, 0, 0, 0));

        selectImg_Zoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Adm.setIcon(null);
        selectImg_Usu.setIcon(null);

        this.setIconImage(new ImageIcon(getClass().getResource("/zoo/Imagens/iCON.png")).getImage());

        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton14.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton16.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonCadZoo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonExcluirZoo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadZoo1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanelCadAdm1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel28 = new javax.swing.JLabel();
        jPanelCadZoo5 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextFieldNomeUsuZoo1 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jTextField30 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jButtonUsu = new javax.swing.JButton();
        jButtonZoo = new javax.swing.JButton();
        jButtonAdm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        selectImg_Zoo = new javax.swing.JLabel();
        selectImg_Adm = new javax.swing.JLabel();
        selectImg_Usu = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nomeZoo = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        UF = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        Valor_entrada = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jText_Abre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jText_Fecha = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nomeZoo1 = new javax.swing.JTextField();
        ID1 = new javax.swing.JTextField();
        endereco1 = new javax.swing.JTextField();
        UF1 = new javax.swing.JTextField();
        cidade1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButtonCadZoo = new javax.swing.JButton();
        jButtonExcluirZoo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField26 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCadAdmSistema = new javax.swing.JButton();
        jButtonCadAdmZoo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelCadZoo6 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JTextField();
        jPasswordFieldConfirmarSenha = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextCodAdm = new javax.swing.JTextField();
        jPanelCadZoo8 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        admZoo_Nome_txf = new javax.swing.JTextField();
        admZoo_CPF_txf = new javax.swing.JTextField();
        admZoo_Email_txf = new javax.swing.JTextField();
        admZoo_senha_txf = new javax.swing.JTextField();
        admZoo_repetirSenha_txf = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        admZoo_sobreNome_txf = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        admZoo_CodAdmZoo_txf = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        admZoo_CodZoo_txf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanelCadZoo1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadZoo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanelCadZoo1.setForeground(new java.awt.Color(0, 102, 0));
        jPanelCadZoo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("Nome");
        jPanelCadZoo1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("Código");
        jPanelCadZoo1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setText("Código Zoológico");
        jPanelCadZoo1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 0));
        jLabel12.setText("Senha");
        jPanelCadZoo1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setText("Repetir Senha");
        jPanelCadZoo1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanelCadZoo1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, -1));
        jPanelCadZoo1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 220, -1));
        jPanelCadZoo1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 220, -1));
        jPanelCadZoo1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 220, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanelCadZoo1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 220, -1));

        jButton4.setText("Cadastrar");
        jPanelCadZoo1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jPanelCadAdm1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadAdm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanelCadAdm1.setForeground(new java.awt.Color(0, 102, 0));
        jPanelCadAdm1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 0));
        jLabel20.setText("Nome");
        jPanelCadAdm1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 0));
        jLabel21.setText("Código");
        jPanelCadAdm1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 0));
        jLabel22.setText("Senha");
        jPanelCadAdm1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 0));
        jLabel23.setText("Repetir Senha");
        jPanelCadAdm1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));
        jPanelCadAdm1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, -1));
        jPanelCadAdm1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 220, -1));
        jPanelCadAdm1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 220, -1));

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanelCadAdm1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 220, -1));

        jButton6.setText("Cadastrar");
        jPanelCadAdm1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 0));
        jLabel24.setText("Cadastro de Administrador");
        jPanelCadAdm1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 180, -1));

        jLabel28.setText("jLabel28");

        jPanelCadZoo5.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadZoo5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Administrador de Zoológico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanelCadZoo5.setForeground(new java.awt.Color(0, 102, 0));
        jPanelCadZoo5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 102, 0));
        jLabel54.setText("Nome");
        jPanelCadZoo5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 102, 0));
        jLabel55.setText("cpf");
        jPanelCadZoo5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 102, 0));
        jLabel56.setText("Sobrenome");
        jPanelCadZoo5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 102, 0));
        jLabel57.setText("Senha");
        jPanelCadZoo5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 102, 0));
        jLabel58.setText("Repetir Senha");
        jPanelCadZoo5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanelCadZoo5.add(jTextFieldNomeUsuZoo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, -1));
        jPanelCadZoo5.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 220, -1));
        jPanelCadZoo5.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, -1));
        jPanelCadZoo5.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, -1));

        jTextField47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField47ActionPerformed(evt);
            }
        });
        jPanelCadZoo5.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 220, -1));

        jButton13.setText("Cadastrar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanelCadZoo5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));
        jPanelCadZoo5.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 0));
        jLabel36.setText("Email");
        jPanelCadZoo5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 102, 0));
        jLabel37.setText("Código Adm de Zoo");
        jPanelCadZoo5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanelCadZoo5.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 220, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 0));
        jLabel38.setText("Código do Zoológico");
        jPanelCadZoo5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        jPanelCadZoo5.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 220, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUsu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUsu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUsu.setText("Usuarios");
        jButtonUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 30));

        jButtonZoo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonZoo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonZoo.setText("Zoologicos");
        jButtonZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZooActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 30));

        jButtonAdm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAdm.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdm.setText("Administradores");
        jButtonAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adiministrador Do sistema");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 30));

        selectImg_Zoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png"))); // NOI18N
        getContentPane().add(selectImg_Zoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 270, 50));

        selectImg_Adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png"))); // NOI18N
        getContentPane().add(selectImg_Adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 270, 50));

        selectImg_Usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png"))); // NOI18N
        getContentPane().add(selectImg_Usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 290, 270, 50));

        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Zoológico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Nome ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Endereço ");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setText("Estado ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 0));
        jLabel15.setText("Cidade ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 0));
        jLabel16.setText("Valor de Entrada : R$");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 30));
        jPanel4.add(nomeZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 270, -1));
        jPanel4.add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, -1));
        jPanel4.add(UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 120, -1));
        jPanel4.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, -1));
        jPanel4.add(Valor_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 50, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Horario Func.");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 20));
        jPanel4.add(jText_Abre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 40, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Até");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 30, -1));
        jPanel4.add(jText_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 40, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 0));
        jLabel29.setText("Dias De Func.");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Segunda-Feira");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Terça-Feira");
        jPanel4.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Quarta-Feira");
        jPanel4.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox4.setSelected(true);
        jCheckBox4.setText("Quinta-Feira");
        jPanel4.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox6.setSelected(true);
        jCheckBox6.setText("Sabado");
        jPanel4.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox7.setSelected(true);
        jCheckBox7.setText("Domingo");
        jPanel4.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(0, 102, 0));
        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Sexta-feira");
        jCheckBox5.setPreferredSize(new java.awt.Dimension(107, 23));
        jPanel4.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 0));
        jButton3.setText("Cadastrar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 90, 40));

        jTabbedPane3.addTab("", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Zoológico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Pesquisar Código do Zoologico");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, 219, 25));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_lupa.png"))); // NOI18N
        jPanel5.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 60, 38, 27));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 0));
        jLabel25.setText("Código ");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 0));
        jLabel19.setText("Nome ");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 0));
        jLabel26.setText("Endereço ");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 0));
        jLabel27.setText("Estado ");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 0));
        jLabel30.setText("Cidade ");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel6.add(nomeZoo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 270, -1));
        jPanel6.add(ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, -1));
        jPanel6.add(endereco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 270, -1));
        jPanel6.add(UF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 120, -1));
        jPanel6.add(cidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 120, -1));

        jButton7.setText("Excluir");
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 373, 340));

        jTabbedPane3.addTab("", jPanel5);

        jPanel1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -20, 390, 430));

        jButtonCadZoo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCadZoo.setForeground(new java.awt.Color(0, 102, 0));
        jButtonCadZoo.setText("Cadastrar Zoologico");
        jButtonCadZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadZooActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        jButtonExcluirZoo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluirZoo.setForeground(new java.awt.Color(0, 102, 0));
        jButtonExcluirZoo.setText("Excluir Zoologico");
        jButtonExcluirZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirZooActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluirZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, -1));

        jTabbedPane1.addTab("", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 271, 30));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/icone_lupa.png"))); // NOI18N
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 0));
        jLabel33.setText("Nome");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel2.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 103, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 0));
        jLabel34.setText("E-mail");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel2.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 103, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 0));
        jLabel35.setText("CPf");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));
        jPanel2.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 0));
        jButton9.setText("Excluir");
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 0));
        jButton10.setText("Bloquear");
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 102, 0));
        jButton12.setText("Desbloquear");
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Pesqusiar CPF");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        jTabbedPane1.addTab("", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadAdmSistema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCadAdmSistema.setForeground(new java.awt.Color(0, 102, 0));
        jButtonCadAdmSistema.setText("Admin de Sistema");
        jButtonCadAdmSistema.setOpaque(false);
        jButtonCadAdmSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAdmSistemaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCadAdmSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));

        jButtonCadAdmZoo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCadAdmZoo.setForeground(new java.awt.Color(0, 102, 0));
        jButtonCadAdmZoo.setText(" Admin de Zoo");
        jButtonCadAdmZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAdmZooActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCadAdmZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Cadastrar:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanelCadZoo6.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadZoo6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanelCadZoo6.setForeground(new java.awt.Color(0, 102, 0));
        jPanelCadZoo6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 102, 0));
        jLabel59.setText("Nome");
        jPanelCadZoo6.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 102, 0));
        jLabel60.setText("CPF");
        jPanelCadZoo6.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 102, 0));
        jLabel61.setText("Sobrenome");
        jPanelCadZoo6.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 102, 0));
        jLabel62.setText("Senha");
        jPanelCadZoo6.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 102, 0));
        jLabel63.setText("Repetir Senha");
        jPanelCadZoo6.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanelCadZoo6.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, -1));
        jPanelCadZoo6.add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 220, -1));
        jPanelCadZoo6.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, -1));
        jPanelCadZoo6.add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, -1));
        jPanelCadZoo6.add(jPasswordFieldConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 220, -1));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 102, 0));
        jButton14.setText("Cadastrar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanelCadZoo6.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, 30));
        jPanelCadZoo6.add(jTextFieldSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 0));
        jLabel39.setText("Email");
        jPanelCadZoo6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 0));
        jLabel40.setText("Código Adm");
        jPanelCadZoo6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanelCadZoo6.add(jTextCodAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 220, -1));

        jTabbedPane2.addTab("", jPanelCadZoo6);

        jPanelCadZoo8.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCadZoo8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Administrador de Zoológico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        jPanelCadZoo8.setForeground(new java.awt.Color(0, 102, 0));
        jPanelCadZoo8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 102, 0));
        jLabel69.setText("Nome");
        jPanelCadZoo8.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 102, 0));
        jLabel70.setText("CPF");
        jPanelCadZoo8.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 102, 0));
        jLabel71.setText("Sobrenome");
        jPanelCadZoo8.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 102, 0));
        jLabel72.setText("Senha");
        jPanelCadZoo8.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 102, 0));
        jLabel73.setText("Repetir Senha");
        jPanelCadZoo8.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jPanelCadZoo8.add(admZoo_Nome_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, -1));
        jPanelCadZoo8.add(admZoo_CPF_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 220, -1));
        jPanelCadZoo8.add(admZoo_Email_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, -1));
        jPanelCadZoo8.add(admZoo_senha_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, -1));

        admZoo_repetirSenha_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admZoo_repetirSenha_txfActionPerformed(evt);
            }
        });
        jPanelCadZoo8.add(admZoo_repetirSenha_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 220, -1));

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 102, 0));
        jButton16.setText("Cadastrar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanelCadZoo8.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));
        jPanelCadZoo8.add(admZoo_sobreNome_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 102, 0));
        jLabel45.setText("Email");
        jPanelCadZoo8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 102, 0));
        jLabel46.setText("Cód. Adm de Zoo");
        jPanelCadZoo8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        jPanelCadZoo8.add(admZoo_CodAdmZoo_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 220, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 102, 0));
        jLabel74.setText("Código do Zoo");
        jPanelCadZoo8.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        jPanelCadZoo8.add(admZoo_CodZoo_txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 220, -1));

        jTabbedPane2.addTab("", jPanelCadZoo8);

        jPanel3.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 380, 400));

        jTabbedPane1.addTab("", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 570, 440));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/botao_voltar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/tela_principal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButtonAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdmActionPerformed
        jTabbedPane1.setSelectedIndex(2);

        selectImg_Adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Zoo.setIcon(null);
        selectImg_Usu.setIcon(null);

    }//GEN-LAST:event_jButtonAdmActionPerformed

    private void jTabbedPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1AncestorAdded

    private void jButtonCadAdmZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAdmZooActionPerformed
        jButtonCadAdmZoo.setText("> Admin de Zoo");
        jButtonCadAdmSistema.setText("Admin de Sistema");
        jTabbedPane2.setVisible(true);
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonCadAdmZooActionPerformed

    private void jButtonCadAdmSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAdmSistemaActionPerformed
        jButtonCadAdmZoo.setText("Admin de Zoo");
        jButtonCadAdmSistema.setText("> Admin de Sistema");
        jTabbedPane2.setVisible(true);
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonCadAdmSistemaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButtonUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuActionPerformed
        jTabbedPane1.setSelectedIndex(1);

        selectImg_Usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Zoo.setIcon(null);
        selectImg_Adm.setIcon(null);

    }//GEN-LAST:event_jButtonUsuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean[] status = new boolean[7];

        Zoologicos zoo = new Zoologicos();
        // verificações de marcação das checkbox
        status[0] = jCheckBox1.isSelected();
        status[1] = jCheckBox2.isSelected();
        status[2] = jCheckBox3.isSelected();
        status[3] = jCheckBox4.isSelected();
        status[4] = jCheckBox5.isSelected();
        status[5] = jCheckBox6.isSelected();
        status[6] = jCheckBox7.isSelected();

        // Definindo os valores na classe Zoologicos
        zoo.setNome(nomeZoo.getText());

        if (jText_Abre.getText().isEmpty()) { // verificação de campo vazio
            zoo.setAbre(-1);
        } else {
            try {
                zoo.setAbre(parseInt(jText_Abre.getText()));
            } catch (Exception e) {
                zoo.setAbre(-1);
            }
        }
        if (jText_Fecha.getText().isEmpty()) { // verificação de campo vazio
            zoo.setFecha(-1);
        } else {
            try {
                zoo.setFecha(parseInt(jText_Fecha.getText()));
            } catch (Exception e) {
                zoo.setFecha(-1);
            }

        }

        if (Valor_entrada.getText().isEmpty()) { // verificação de campo vazio
            zoo.setValor_entrada(-1);
        } else {
            try {
                zoo.setValor_entrada(Float.parseFloat(Valor_entrada.getText()));
            } catch (Exception e) {
                zoo.setValor_entrada(-1);
            }

        }

        zoo.setEndereco(endereco.getText());
        zoo.setCidade(cidade.getText());
        zoo.setUF(UF.getText());

        zoo.setStatus(status);

        if (zoo.getNome().isEmpty() || zoo.getAbre() == 0 || zoo.getFecha() == 0 || zoo.getEndereco().isEmpty() || zoo.getCidade().isEmpty() || zoo.getUF().isEmpty() || zoo.getValor_entrada() == 0) {
            JOptionPane.showMessageDialog(null, "Os Campos Em Vermelho Ficaram Em Branco E Devem Ser Preenchidos");

            if (zoo.getNome().isEmpty()) {
                nomeZoo.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (zoo.getAbre() == -1) {
                jText_Abre.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (zoo.getFecha() == -1) {
                jText_Fecha.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (zoo.getEndereco().isEmpty()) {
                endereco.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (zoo.getCidade().isEmpty()) {
                cidade.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (zoo.getUF().isEmpty()) {
                UF.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (zoo.getValor_entrada() == 0) {
                Valor_entrada.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
        } else {

            InicioProg.addZoo(zoo);

            nomeZoo.setText("");
            jText_Abre.setText("");
            jText_Fecha.setText("");
            endereco.setText("");
            cidade.setText("");
            UF.setText("");
            Valor_entrada.setText("");

            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField47ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void admZoo_repetirSenha_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admZoo_repetirSenha_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admZoo_repetirSenha_txfActionPerformed

    private void jButtonZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZooActionPerformed
        jTabbedPane1.setSelectedIndex(0);

        selectImg_Zoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/Imagens/Selected.png")));
        selectImg_Usu.setIcon(null);
        selectImg_Adm.setIcon(null);

    }//GEN-LAST:event_jButtonZooActionPerformed

    private void jButtonCadZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadZooActionPerformed
        jTabbedPane3.setVisible(true);
        jTabbedPane3.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonCadZooActionPerformed

    private void jButtonExcluirZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirZooActionPerformed
        jTabbedPane3.setVisible(true);
        jTabbedPane3.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonExcluirZooActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        jButton14.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AdmSistema usuario = new AdmSistema(jTextFieldNome.getText(), jTextFieldSobrenome.getText(), jTextFieldCPF.getText(), jPasswordFieldSenha.getText(), jTextFieldEmail.getText());
        String confirmaSenha = jPasswordFieldConfirmarSenha.getText();

        if (usuario.getNome().isEmpty() || usuario.getSobrenome().isEmpty() || usuario.getCpf().isEmpty() || usuario.getEmail().isEmpty() || usuario.getSenha().isEmpty() || confirmaSenha.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os Campos Em Vermelho Devem Ser Preenchidos");

            if (usuario.getNome().isEmpty()) {
                jTextFieldNome.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getSobrenome().isEmpty()) {
                jTextFieldSobrenome.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getCpf().isEmpty()) {
                jTextFieldCPF.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getEmail().isEmpty()) {
                jTextFieldEmail.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getSenha().isEmpty()) {
                jPasswordFieldSenha.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (confirmaSenha.isEmpty()) {
                jPasswordFieldConfirmarSenha.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (jTextCodAdm.getText().isEmpty()) {
                jTextCodAdm.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
        } else {
            if (usuario.getSenha().equals(confirmaSenha)) {

                //Adição de um novo user
                usuario.setId(InicioProg.usu.size() + 1);
                InicioProg.addUser(usuario);

            } else {
                JOptionPane.showMessageDialog(null, "Senhas nao coincidem!");
                jPasswordFieldSenha.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
                jPasswordFieldConfirmarSenha.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
                return;
            }
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");
            jTextFieldSobrenome.setText("");
            jTextFieldCPF.setText("");
            jPasswordFieldSenha.setText("");
            jPasswordFieldConfirmarSenha.setText("");
            jTextCodAdm.setText("");
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        AdmZoo usuario = new AdmZoo(admZoo_Nome_txf.getText(), admZoo_sobreNome_txf.getText(), admZoo_CPF_txf.getText(), admZoo_senha_txf.getText(), admZoo_Email_txf.getText());
        String confirmaSenha = admZoo_repetirSenha_txf.getText();

        if (usuario.getNome().isEmpty() || usuario.getSobrenome().isEmpty() || usuario.getCpf().isEmpty() || usuario.getEmail().isEmpty() || usuario.getSenha().isEmpty() || confirmaSenha.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os Campos Em Vermelho Devem Ser Preenchidos");

            if (usuario.getNome().isEmpty()) {
                admZoo_Nome_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getSobrenome().isEmpty()) {
                admZoo_sobreNome_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getCpf().isEmpty()) {
                admZoo_CPF_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getEmail().isEmpty()) {
                admZoo_Email_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (usuario.getSenha().isEmpty()) {
                admZoo_senha_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (confirmaSenha.isEmpty()) {
                admZoo_repetirSenha_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (admZoo_CodZoo_txf.getText().isEmpty()) {
                admZoo_CodZoo_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }
            if (admZoo_CodAdmZoo_txf.getText().isEmpty()) {
                admZoo_CodAdmZoo_txf.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
            }

        } else {
            if (usuario.getSenha().equals(confirmaSenha)) {

                usuario.setCodUsuZoo(parseInt(admZoo_CodZoo_txf.getText())); //Codigo de admin

                //Adição de um novo user
                usuario.setId(InicioProg.usu.size() + 1);
                InicioProg.addUser(usuario);

            } else {
                JOptionPane.showMessageDialog(null, "Senhas nao coincidem!");
                jPasswordFieldSenha.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
                jPasswordFieldConfirmarSenha.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
                return;
            }
            admZoo_Nome_txf.setText("");
            admZoo_sobreNome_txf.setText("");
            admZoo_CPF_txf.setText("");
            admZoo_Email_txf.setText("");
            admZoo_senha_txf.setText("");
            admZoo_repetirSenha_txf.setText("");
            admZoo_sobreNome_txf.setText("");
            admZoo_CodAdmZoo_txf.setText("");
            admZoo_CodZoo_txf.setText("");
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InicioProg.telaAS.setVisible(false);
        InicioProg.principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID1;
    private javax.swing.JTextField UF;
    private javax.swing.JTextField UF1;
    private javax.swing.JTextField Valor_entrada;
    private javax.swing.JTextField admZoo_CPF_txf;
    private javax.swing.JTextField admZoo_CodAdmZoo_txf;
    private javax.swing.JTextField admZoo_CodZoo_txf;
    private javax.swing.JTextField admZoo_Email_txf;
    private javax.swing.JTextField admZoo_Nome_txf;
    private javax.swing.JTextField admZoo_repetirSenha_txf;
    private javax.swing.JTextField admZoo_senha_txf;
    private javax.swing.JTextField admZoo_sobreNome_txf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cidade1;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField endereco1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdm;
    private javax.swing.JButton jButtonCadAdmSistema;
    private javax.swing.JButton jButtonCadAdmZoo;
    private javax.swing.JButton jButtonCadZoo;
    private javax.swing.JButton jButtonExcluirZoo;
    private javax.swing.JButton jButtonUsu;
    private javax.swing.JButton jButtonZoo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCadAdm1;
    private javax.swing.JPanel jPanelCadZoo1;
    private javax.swing.JPanel jPanelCadZoo5;
    private javax.swing.JPanel jPanelCadZoo6;
    private javax.swing.JPanel jPanelCadZoo8;
    private javax.swing.JTextField jPasswordFieldConfirmarSenha;
    private javax.swing.JTextField jPasswordFieldSenha;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextCodAdm;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeUsuZoo1;
    private javax.swing.JTextField jTextFieldSobrenome;
    private javax.swing.JTextField jText_Abre;
    private javax.swing.JTextField jText_Fecha;
    private javax.swing.JTextField nomeZoo;
    private javax.swing.JTextField nomeZoo1;
    private javax.swing.JLabel selectImg_Adm;
    private javax.swing.JLabel selectImg_Usu;
    private javax.swing.JLabel selectImg_Zoo;
    // End of variables declaration//GEN-END:variables
}
